name: Deploiement VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploiement via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 185.157.244.202
          username: etudiant
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/webclients
            git pull origin main
            /home/etudiant/.bun/bin/bun install
            /home/etudiant/.bun/bin/bun run build
            sudo systemctl restart webclients