name: Déploiement VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion au VPS et déploiement
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/webclients
            git pull https://${{ secrets.GITHUB_TOKEN }}@github.com/hillairet-enzo/WebClients.git main
            /home/etudiant/.bun/bin/bun install
            /home/etudiant/.bun/bin/bun run build
            echo "${{ secrets.VPS_PASSWORD }}" | sudo -S systemctl restart webclients